[phases.setup]
nixPkgs = ['...', 'libglvnd', 'glib', 'libxcb', 'libX11', 'libXrender', 'libXrandr', 'libXext']
aptPkgs = ['libxcb1', 'libxcb-xkb1', 'libx11-6', 'libxrender1', 'libxrandr2', 'libxext6']
